#!/system/bin/sh
# Script to initiate rngd at boot by Ryuinferno @ XDA 2013

LOG=/data/local/seeder.log

if pgrep qrngd > /dev/null; then
  echo "qrngd already running! Seeder will not be started!" >> $LOG
  exit 1
fi

if [ -e /system/bin/qrngd -o -e /system/xbin/qrngd ]; then
  echo "qrngd found in /system! Seeder will not be started!" >> $LOG
  exit
fi

rngd -t 2 -T 1 -s 256 --fill-watermark=80%
sleep 2
echo -8 > /proc/$(pgrep rngd)/oom_adj
renice 5 `pidof rngd`

